name: e2e tests
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 18.0.0

      - name: npm install
        run: npm install

      - name: run tests
        run: |
          cd e2e
          npx codeceptjs run --steps
